### ISSUE TITLE
[Dashboard] - Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Ruhneko** [carlobearr/parcel#2]
**By: Jamie & Curry Co.**

**Branch:** feature/book-a-delivery

**Browser:** Microsoft Edge

**Type:**
(**Coding Error** / Design Issue / Suggestion)

**Severity:**
(**Fatal** / Serious / Minor)

**Description:**
Running the app returns 500 Internal server error.

**Steps to Replicate:**
1. pull from the feature/book-a-delivery branch
2. follow the provided steps to run the project: https://docs.google.com/document/d/1hcdIgr8CTR8LVgTo75egcRaaP7IwLCm04b88CdIPF3M/edit
3. Go to [http://localhost:3000/](http://localhost:3000/)

**Expected Output:** Loads login page

**Actual Output:** Loads dashboard with 500 Internal server error.

**Actual Results:**
![image](https://user-images.githubusercontent.com/60461144/104844967-f1234700-590d-11eb-807e-21d418b3c97a.png)

**Terminal Error:**
![image](https://user-images.githubusercontent.com/60461144/104845015-33e51f00-590e-11eb-9673-4e160e5a37fd.png)

**Comment by ronellroxas** [comment]
Try renaming env file to ".env" then restart servers

**Comment by Ruhneko** [comment]
thanks, app is running now
